"""Entities and value objects for chat slice. No framework or ORM dependency."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import UTC, datetime
from enum import StrEnum
from uuid import UUID, uuid4

from shared.domain.proficiency import ProficiencyLevel
from shared.errors import ValidationError

# ---------- domain constants ----------

MAX_USER_MESSAGE_LENGTH = 1000
MAX_TOPIC_LABEL_LENGTH = 60
MAX_TOPIC_DESCRIPTION_LENGTH = 255
MAX_GOAL_LABEL_LENGTH = 60
MAX_GOAL_DESCRIPTION_LENGTH = 255
MAX_FEEDBACK_CORRECTION_EXPLANATION_LENGTH = 500
MAX_FEEDBACK_SUGGESTION_LENGTH = 280
MAX_FEEDBACK_CORRECTIONS = 3
MAX_GOAL_LENGTH = 500  # custom goal sent by the user


class ConversationMode(StrEnum):
    """Conversation mode."""

    FREE = "FREE"
    TOPIC = "TOPIC"
    GOAL = "GOAL"


class ConversationStatus(StrEnum):
    """Conversation lifecycle status."""

    ACTIVE = "active"
    COMPLETED = "completed"
    ABANDONED = "abandoned"


class GoalStatus(StrEnum):
    """Progress regarding communicative goal."""

    IN_PROGRESS = "in_progress"
    ACHIEVED = "achieved"
    ABANDONED = "abandoned"


# ---------- value objects ----------


@dataclass(frozen=True, slots=True)
class FeedbackCorrection:
    """A grammar or vocabulary correction found in student message."""

    original: str
    corrected: str
    explanation: str


@dataclass(frozen=True, slots=True)
class TurnFeedback:
    """Pedagogical analysis generated by AI for a turn."""

    corrections: list[FeedbackCorrection]
    suggestion: str | None


# ---------- main entities ----------


@dataclass(slots=True)
class Conversation:
    """Conversation session between student and AI."""

    id: UUID
    user_id: UUID
    mode: ConversationMode
    level: ProficiencyLevel
    topic: str | None
    goal: str | None
    goal_status: GoalStatus
    status: ConversationStatus
    created_at: datetime
    updated_at: datetime
    goals: list[str] = field(default_factory=list)
    goals_progress: list[bool] = field(default_factory=list)

    @classmethod
    def create(
        cls,
        *,
        user_id: UUID,
        mode: ConversationMode,
        level: ProficiencyLevel,
        topic: str | None = None,
        goal: str | None = None,
        goals: list[str] | None = None,
    ) -> Conversation:
        """Factory enforcing domain invariants."""
        if mode == ConversationMode.TOPIC and not (topic or "").strip():
            raise ValidationError("'topic' is required for TOPIC mode conversations.")
        
        cleaned_goals: list[str] = []
        if goals:
            cleaned_goals = [g.strip() for g in goals if g and g.strip()]
            for g in cleaned_goals:
                if len(g) > MAX_GOAL_LENGTH:
                    raise ValidationError(
                        f"Goal '{g[:30]}...' exceeds {MAX_GOAL_LENGTH} characters."
                    )

        if mode == ConversationMode.GOAL and not (goal or "").strip() and not cleaned_goals:
            raise ValidationError(
                "'goal' or 'goals' is required for GOAL mode conversations."
            )

        goal_str = goal.strip() if goal else None
        if not goal_str and cleaned_goals:
            goal_str = " | ".join(cleaned_goals)
        elif goal_str and not cleaned_goals:
            cleaned_goals = [goal_str]

        if goal_str and len(goal_str) > MAX_GOAL_LENGTH:
            raise ValidationError(f"'goal' exceeds {MAX_GOAL_LENGTH} characters.")

        now = datetime.now(UTC)
        return cls(
            id=uuid4(),
            user_id=user_id,
            mode=mode,
            level=level,
            topic=topic.strip() if topic else None,
            goal=goal_str,
            goals=cleaned_goals,
            goals_progress=[False] * len(cleaned_goals),
            goal_status=GoalStatus.IN_PROGRESS,
            status=ConversationStatus.ACTIVE,
            created_at=now,
            updated_at=now,
        )

    def abandon(self) -> None:
        """Marks conversation as abandoned."""
        if self.status != ConversationStatus.ACTIVE:
            from modules.chat.domain.errors import InvalidConversationState

            raise InvalidConversationState(
                f"Conversation cannot be abandoned: current status is '{self.status}'."
            )
        self.status = ConversationStatus.ABANDONED
        self.goal_status = GoalStatus.ABANDONED
        self.updated_at = datetime.now(UTC)

    def complete(self, *, goal_achieved: bool = False) -> None:
        """Marks conversation as completed."""
        self.status = ConversationStatus.COMPLETED
        if goal_achieved:
            self.goal_status = GoalStatus.ACHIEVED
        self.updated_at = datetime.now(UTC)


@dataclass(slots=True)
class ConversationTurn:
    """Pair of student-message / AI-reply inside a Conversation."""

    id: UUID
    conversation_id: UUID
    turn_index: int
    user_message: str
    ai_reply: str
    feedback: TurnFeedback | None
    created_at: datetime

    @classmethod
    def create(
        cls,
        *,
        conversation_id: UUID,
        turn_index: int,
        user_message: str,
        ai_reply: str,
        feedback: TurnFeedback | None,
    ) -> ConversationTurn:
        """Factory validating student message."""
        msg = (user_message or "").strip()
        if not msg:
            raise ValidationError("'user_message' cannot be empty.")
        if len(msg) > MAX_USER_MESSAGE_LENGTH:
            raise ValidationError(
                f"'user_message' exceeds {MAX_USER_MESSAGE_LENGTH} characters."
            )
        now = datetime.now(UTC)
        return cls(
            id=uuid4(),
            conversation_id=conversation_id,
            turn_index=turn_index,
            user_message=msg,
            ai_reply=ai_reply,
            feedback=feedback,
            created_at=now,
        )


@dataclass(slots=True)
class ChatTopic:
    """Predefined conversation topic (TOPIC mode)."""

    id: UUID
    label: str
    description: str
    level_hint: ProficiencyLevel

    @classmethod
    def create(
        cls,
        *,
        label: str,
        description: str,
        level_hint: ProficiencyLevel,
    ) -> ChatTopic:
        lbl = (label or "").strip()
        if not lbl or len(lbl) > MAX_TOPIC_LABEL_LENGTH:
            raise ValidationError(
                f"Topic 'label' must be between 1 and {MAX_TOPIC_LABEL_LENGTH} characters."
            )
        desc = (description or "").strip()
        if not desc or len(desc) > MAX_TOPIC_DESCRIPTION_LENGTH:
            raise ValidationError(
                f"Topic 'description' must be between 1 and "
                f"{MAX_TOPIC_DESCRIPTION_LENGTH} characters."
            )
        return cls(id=uuid4(), label=lbl, description=desc, level_hint=level_hint)


@dataclass(slots=True)
class ChatGoal:
    """Predefined communicative goal (GOAL mode)."""

    id: UUID
    label: str
    description: str
    level_hint: ProficiencyLevel
    targets: list[str] = field(default_factory=list)

    @classmethod
    def create(
        cls,
        *,
        label: str,
        description: str,
        level_hint: ProficiencyLevel,
        targets: list[str] | None = None,
    ) -> ChatGoal:
        lbl = (label or "").strip()
        if not lbl or len(lbl) > MAX_GOAL_LABEL_LENGTH:
            raise ValidationError(
                f"Goal 'label' must be between 1 and {MAX_GOAL_LABEL_LENGTH} characters."
            )
        desc = (description or "").strip()
        if not desc or len(desc) > MAX_GOAL_DESCRIPTION_LENGTH:
            raise ValidationError(
                f"Goal 'description' must be between 1 and "
                f"{MAX_GOAL_DESCRIPTION_LENGTH} characters."
            )
        cleaned_targets: list[str] = []
        if targets:
            cleaned_targets = [t.strip() for t in targets if t and t.strip()]
        return cls(
            id=uuid4(),
            label=lbl,
            description=desc,
            level_hint=level_hint,
            targets=cleaned_targets,
        )
