"""create study cards with sentence chunks

Revision ID: 0829b32bbd4f
Revises: e320572aa0f3
Create Date: 2026-09-13 18:04:26.341906

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0829b32bbd4f"
down_revision: str | Sequence[str] | None = "e320572aa0f3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "study_cards",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sentence", sa.String(length=500), nullable=False),
        sa.Column("sentence_normalized", sa.String(length=500), nullable=False),
        sa.Column("translation", sa.String(length=240), nullable=False),
        sa.Column("focus_term", sa.String(length=120), nullable=False),
        sa.Column("level", sa.String(length=2), nullable=False),
        sa.Column("theme", sa.String(length=120), nullable=False),
        sa.Column("sentence_chunks", sa.JSON(), nullable=False),
        sa.Column("repetitions", sa.Integer(), nullable=False),
        sa.Column("lapses", sa.Integer(), nullable=False),
        sa.Column("ease_factor", sa.Float(), nullable=False),
        sa.Column("interval_days", sa.Integer(), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_study_cards")),
    )
    with op.batch_alter_table("study_cards", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_study_cards_due_at"), ["due_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_study_cards_level"), ["level"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_study_cards_sentence_normalized"), ["sentence_normalized"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("study_cards", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_study_cards_sentence_normalized"))
        batch_op.drop_index(batch_op.f("ix_study_cards_level"))
        batch_op.drop_index(batch_op.f("ix_study_cards_due_at"))

    op.drop_table("study_cards")
    # ### end Alembic commands ###
