"""create vocabulary entries

Revision ID: e320572aa0f3
Revises:
Create Date: 2026-09-13 16:15:04.630686

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e320572aa0f3"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vocabulary_entries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("term", sa.String(length=120), nullable=False),
        sa.Column("term_normalized", sa.String(length=120), nullable=False),
        sa.Column("translation", sa.String(length=240), nullable=False),
        sa.Column("example", sa.String(length=500), nullable=True),
        sa.Column("level", sa.String(length=2), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vocabulary_entries")),
    )
    with op.batch_alter_table("vocabulary_entries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_vocabulary_entries_term_normalized"), ["term_normalized"], unique=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("vocabulary_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_vocabulary_entries_term_normalized"))

    op.drop_table("vocabulary_entries")
    # ### end Alembic commands ###
