"""create_chat_tables

Revision ID: af36a602c24d
Revises: c3d4e5f6a1b2
Create Date: 2026-09-13 23:12:46.089348

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "af36a602c24d"
down_revision: str | Sequence[str] | None = "c3d4e5f6a1b2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_goals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.String(length=60), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("level_hint", sa.String(length=4), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_goals")),
    )
    op.create_table(
        "chat_topics",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.String(length=60), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("level_hint", sa.String(length=4), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_topics")),
    )
    op.create_table(
        "conversations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("level", sa.String(length=4), nullable=False),
        sa.Column("topic", sa.String(length=500), nullable=True),
        sa.Column("goal", sa.String(length=500), nullable=True),
        sa.Column("goal_status", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_conversations_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
    )
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_conversations_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_conversations_user_id"), ["user_id"], unique=False)

    op.create_table(
        "conversation_turns",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("turn_index", sa.Integer(), nullable=False),
        sa.Column("user_message", sa.String(length=1000), nullable=False),
        sa.Column("ai_reply", sa.String(length=4000), nullable=False),
        sa.Column("feedback", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_conversation_turns_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversation_turns")),
    )
    with op.batch_alter_table("conversation_turns", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_conversation_turns_conversation_id"), ["conversation_id"], unique=False
        )

    with op.batch_alter_table("seen_words", schema=None) as batch_op:
        batch_op.alter_column(
            "seen_count", existing_type=sa.INTEGER(), server_default=None, existing_nullable=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("seen_words", schema=None) as batch_op:
        batch_op.alter_column(
            "seen_count",
            existing_type=sa.INTEGER(),
            server_default=sa.text("'1'"),
            existing_nullable=False,
        )

    with op.batch_alter_table("conversation_turns", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_conversation_turns_conversation_id"))

    op.drop_table("conversation_turns")
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_conversations_user_id"))
        batch_op.drop_index(batch_op.f("ix_conversations_status"))

    op.drop_table("conversations")
    op.drop_table("chat_topics")
    op.drop_table("chat_goals")
    # ### end Alembic commands ###
