"""add users and scope data per user

Revision ID: cbf65869f0a5
Revises: 0829b32bbd4f
Create Date: 2026-09-13 20:13:47.840193

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cbf65869f0a5"
down_revision: str | Sequence[str] | None = "0829b32bbd4f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(length=40), nullable=False),
        sa.Column("password_hash", sa.String(length=120), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_username"), ["username"], unique=True)

    with op.batch_alter_table("study_cards", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Uuid(), nullable=False))
        batch_op.create_index(batch_op.f("ix_study_cards_user_id"), ["user_id"], unique=False)
        batch_op.create_foreign_key(
            batch_op.f("fk_study_cards_user_id_users"),
            "users",
            ["user_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("vocabulary_entries", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Uuid(), nullable=False))
        batch_op.drop_index(batch_op.f("ix_vocabulary_entries_term_normalized"))
        batch_op.create_index(
            batch_op.f("ix_vocabulary_entries_term_normalized"), ["term_normalized"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_vocabulary_entries_user_id"), ["user_id"], unique=False
        )
        batch_op.create_unique_constraint(
            "uq_vocabulary_entries_user_term", ["user_id", "term_normalized"]
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_vocabulary_entries_user_id_users"),
            "users",
            ["user_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("vocabulary_entries", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_vocabulary_entries_user_id_users"), type_="foreignkey"
        )
        batch_op.drop_constraint("uq_vocabulary_entries_user_term", type_="unique")
        batch_op.drop_index(batch_op.f("ix_vocabulary_entries_user_id"))
        batch_op.drop_index(batch_op.f("ix_vocabulary_entries_term_normalized"))
        batch_op.create_index(
            batch_op.f("ix_vocabulary_entries_term_normalized"), ["term_normalized"], unique=1
        )
        batch_op.drop_column("user_id")

    with op.batch_alter_table("study_cards", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_study_cards_user_id_users"), type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_study_cards_user_id"))
        batch_op.drop_column("user_id")

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))

    op.drop_table("users")
    # ### end Alembic commands ###
