"""add goals targets and progress

Revision ID: c7bde645296f
Revises: d4e5f6a1b2c3
Create Date: 2026-09-14 16:35:36.009438

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c7bde645296f"
down_revision: str | Sequence[str] | None = "d4e5f6a1b2c3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chat_goals", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("targets", sa.JSON(), nullable=False, server_default=sa.text("'[]'"))
        )

    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("goals", sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column("goals_progress", sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.drop_column("goals_progress")
        batch_op.drop_column("goals")

    with op.batch_alter_table("chat_goals", schema=None) as batch_op:
        batch_op.drop_column("targets")

    # ### end Alembic commands ###
